### ISSUE TITLE
You can add a problem description here

### ISSUE THREAD

**Issue by mangodager** [mangodager/smartx-dotnet#1]
You can add a problem description here

**Comment by Ambassador-pi** [comment]
3.20d bin folder covers 3.20c. After running the ore pool program for a period of time, exceptions are thrown repeatedly. After deleting the data file, it returns to normal, but exceptions will be thrown again soon. Using the data file with exception thrown by 3.20d to run the 3.20c program is normal, and there are no exceptions. Judge that there should be a bug in the 3.20d ore pool module. The error information and location are as follows:

08-06 21:39:44 318 System.Exception: GetMcBlock(587291) return null
at ETModel.Pool.GetMinerReward_PPLNS(Int64 minHeight, Int64 maxHeight) in D:\smartx-dotnet3.20d-master\smartx-dotnet-master\Core\Core\Mining\Pool.cs:line 280
at ETModel.Pool.MinerReward(Boolean saveDB) in D:\smartx-dotnet3.20d-master\smartx-dotnet-master\Core\Core\Mining\Pool.cs:line 210
at ETModel.Pool.MinerReward(Boolean saveDB) in D:\smartx-dotnet3.20d-master\smartx-dotnet-master\Core\Core\Mining\Pool.cs:line 189
at ETModel.Pool.ThreadRun(Object data) in D:\smartx-dotnet3.20d-master\smartx-dotnet-master\Core\Core\Mining\Pool.cs:line 89
ThreadStart at offset 60 in file:line:column :0:0
RunInternal at offset 118 in file:line:column :0:0
ThreadStart_Context at offset 61 in file:line:column :0:0
ThreadRun at offset 114 in file:line:column D:\smartx-dotnet3.20d-master\smartx-dotnet-master\Core\Core\Mining\Pool.cs:89:21
Error at offset 104 in file:line:column D:\smartx-dotnet3.20d-master\smartx-dotnet-master\Base\Log.cs:31:4
Error at offset 97 in file:line:column D:\smartx-dotnet3.20d-master\smartx-dotnet-master\Base\Logger\NLogAdapter.cs:39:4

**Comment by Ambassador-pi** [comment]
Pool mode：PPLNS
